# Generated by Django 6.0.3 on 2026-03-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_agendaitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registration',
            options={'ordering': ['registered_at']},
        ),
        migrations.AddField(
            model_name='registration',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('waitlisted', 'Waitlisted')], default='confirmed', max_length=20),
        ),
    ]
