# Generated by Django 6.0.3 on 2026-03-20 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_registration_options_registration_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='requires_registration',
            field=models.BooleanField(default=True, help_text='Uncheck this if the event is open to everyone (no RSVP needed).'),
        ),
        migrations.AlterField(
            model_name='event',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum attendees allowed. Leave blank for unlimited.', null=True),
        ),
    ]
