# Generated by Django 6.0.3 on 2026-04-14 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_event_category_event_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='quarter',
            field=models.CharField(blank=True, choices=[('Q1', '1st Quarter'), ('Q2', '2nd Quarter'), ('Q3', '3rd Quarter'), ('Q4', '4th Quarter')], help_text='Select the academic quarter for this event', max_length=2, null=True),
        ),
    ]
